version: "3.7"

services:
  backend:
    build:
      context: .
    volumes:
      - ./node-server/src:/home/node/app/src
    container_name: backend
    env_file: .env
    expose:
      - 4000
    ports:
      - "4000:4000"
    command: yarn dev
    depends_on:
      - db
      - cache
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  db:
    driver: local
